### PR TITLE
Payload bay doors opening video.

### PR DESCRIPTION
**Pull request by gaetanverbrugghe**

### CODE REVIEW

**Comment by Haroenv** [comment]
Probably good, also added to the _data file?

**Comment by gaetanverbrugghe** [comment]
It's in another pull request. Couldn't figure out how to add it to this one.

**Comment by Haroenv** [comment]
Super! I can recommend git-it to figure out git locally ❤️

**Comment by gaetanverbrugghe** [comment]
Why isn't the video showing in src/vid?

**Comment by Haroenv** [comment]
Oops in the wrong directory, I'll fix it

**Pull request merged**
